# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u8ba8\u8bba\u540d\u79f0')),
                ('desc', models.TextField(verbose_name='\u8ba8\u8bba\u63cf\u8ff0')),
                ('starting_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8ba8\u8bba',
                'verbose_name_plural': '\u8ba8\u8bba',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('url', models.TextField(verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('type', models.TextField(verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('upload_date', models.DateTimeField(verbose_name='\u4e0a\u4f20\u65f6\u95f4\u65f6\u95f4')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6',
                'verbose_name_plural': '\u6587\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('title', models.TextField(verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('desc', models.TextField(verbose_name='\u9879\u76ee\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee',
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u56de\u590d\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u56de\u590d\u5185\u5bb9')),
                ('reply_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u56de\u590d\u65f6\u95f4')),
                ('floor_place', models.IntegerField(default=1, verbose_name='\u6240\u5728\u697c\u5c42')),
            ],
            options={
                'verbose_name': '\u56de\u590d',
                'verbose_name_plural': '\u56de\u590d',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='\u4efb\u52a1\u540d\u79f0')),
                ('starting_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('deadline', models.DateTimeField(verbose_name='\u622a\u6b62\u65f6\u95f4')),
                ('is_end', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ed3\u675f')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1',
                'verbose_name_plural': '\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53c2\u4e0e\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u7528\u6237\u5173\u8054',
                'verbose_name_plural': '\u9879\u76ee\u7528\u6237\u5173\u8054',
            },
        ),
    ]
