# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171129_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
