# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
