# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20171204_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='project_belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.Project', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=None, verbose_name='\u622a\u6b62\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.Project', verbose_name='\u9879\u76ee'),
        ),
    ]
