# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171206_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u622a\u6b62\u65f6\u95f4'),
        ),
    ]
