# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20171206_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=None, verbose_name='\u622a\u6b62\u65f6\u95f4'),
        ),
    ]
