# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 06:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20171206_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='floor_place',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='title',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5c42\u4e3b'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(upload_to='course/resource/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6'),
        ),
    ]
