# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20171221_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.TextField(default='', verbose_name='\u4efb\u52a1\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.FileField(upload_to='project/file/%Y/%m', verbose_name='\u8d44\u6e90\u6587\u4ef6'),
        ),
    ]
